title: Better YouTube Search Chrome Extension Developer Documentation
description: Better YouTube Search Chrome Extension Developer Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  YouTube Search Fixer Google Chrome Extension Repository: https://github.com/ChadWKirk/better-youtube-search-chrome-extension
