title: YouTube Search Fixer Google Chrome Extension Developer Documentation
description: YouTube Search Fixer Google Chrome Extension Developer Documentation
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  YouTube Search Fixer Google Chrome Extension Repository: https://github.com/ChadWKirk/youtube-search-fixer-chrome-extension
